addArea:
    path:     /areas/addArea/
    defaults: { _controller:AreaBundle:Default:addArea }

editarMenu:
    path:     /areas/editarMenu/
    defaults: { _controller:AreaBundle:Default:editarMenu }

updateArea:
    path:     /areas/editarArea/
    defaults: { _controller:AreaBundle:Default:editarArea }
