imports:
    - { resource: parameters_production.yml }
    - { resource: config.yml }

monolog:
    handlers:
        main:
            action_level: %monolog_action_level%
doctrine:
    dbal:
        url: "%database_url%"

