imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OfertaBundle/Resources/config/services.yml" }
    - { resource: "@DemandaBundle/Resources/config/services.yml" }
    - { resource: "@ComentarioBundle/Resources/config/services.yml" }
    - { resource: "@AreaBundle/Resources/config/services.yml" }
    - { resource: "@DisciplinaBundle/Resources/config/services.yml" }
    - { resource: "@RamaBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#brochures_directory: '%kernel.root_dir%/../web/uploads/brochures'

parameters:
    locale: en
    brochures_directory: '%kernel.root_dir%/../web/uploads/brochures/oferta/'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"

# Doctrine Configuration
doctrine:
    dbal:
        url: "%database_url%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true


    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType


# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

twig:
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

knp_paginator:
    page_range: 5                      # rango por defecto de paginas en los controles del paginador
    default_options:
        page_name: page                # nombre del parámetro de la URL para la página
        sort_field_name: sort          # nombre del parámetro de la URL para la ordenación
        sort_direction_name: direction # nombre del parámetro de la URL para la dirección(ASC o DESC)
        distinct: true                 # Garantizar resultados distintos
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig' # sort link template

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: lorenrr1@gmail.com
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            from_email:
                address:        lorenrr1@gmail.com
                sender_name:    Demo Registration 
    resetting:
        email:
            from_email:
                address:        lorenrr1@gmail.com
                sender_name:    Demo Resetting       
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   email/password_resetting.email.twig
    registration:
        confirmation:
            template:   UserBundle:Registration:email.txt.twig