
homepage:
    pattern:   /
    defaults:  { _controller: FOSUserBundle:Security:login }
    
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

comentario:
    resource: "@ComentarioBundle/Resources/config/routing.yml"
    prefix:   /

disciplina:
    resource: "@DisciplinaBundle/Resources/config/routing.yml"
    prefix:   /

rama:
    resource: "@RamaBundle/Resources/config/routing.yml"
    prefix:   /

area:
    resource: "@AreaBundle/Resources/config/routing.yml"
    prefix:   /

demanda:
    resource: "@DemandaBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin