portada:
    path:     /demandas/
    defaults: { _controller: OfertaBundle:Default:portada }

addOferta:
    path:     /addOferta/
    defaults: { _controller: OfertaBundle:Default:subirOferta }

mostrarOfertas:
    path:     /mostrarOfertas/
    defaults: { _controller: OfertaBundle:Default:mostrarOfertas }

showOferta:
    path:     /showOferta/
    defaults: { _controller: OfertaBundle:Default:showOferta }

deleteComment:
    path:     /deleteComment/
    defaults: { _controller: OfertaBundle:Default:deleteComment }

select_ramas:
    path:     /selectRamas/
    defaults: { _controller: OfertaBundle:Default:selectRamas }

select_disciplinas:
    path:     /selectDisciplinas/
    defaults: { _controller: OfertaBundle:Default:selectDisciplinas }

oferta_lista:
    path:     /area_lista/
    defaults: { _controller: OfertaBundle:Default:searchArea }

oferta_search:
    path:     /search_oferta/
    defaults: { _controller: OfertaBundle:Default:searchOferta }

oferta_search:
    path:     /search_oferta/
    defaults: { _controller: OfertaBundle:Default:searchOferta }

send_email:
    path:     /send_email/
    defaults: { _controller: OfertaBundle:Default:sendEmail }


grafica_ofertas:
    path:     /grafica_ofertas/
    defaults: { _controller: OfertaBundle:Default:chart }


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile